sudo: required
language: generic

services:
  - docker

before_install:
- docker build -t devopsdmc/fibapptest -f ./client/Dockerfile.dev ./client

script:
- docker run -e CI=true devopsdmc/fibapp npm test

after_success:
  - docker build -t devopsdmc/fibapp ./client
  - docker build -t devopsdmc/fibnginx ./nginx
  - docker build -t devopsdmc/fibserver ./server
  - docker build -t devopsdmc/fibworker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push devopsdmc/fibapp
  - docker push devopsdmc/fibnginx
  - docker push devopsdmc/fibserver
  - docker push devopsdmc/fibworker