version: '3'

services:
  client:
    image: 'devopsdmc/fibapp'
    mem_limit: 128m
    hostname: client
  
  server:
    image: 'devopsdmc/fibserver'
    mem_limit: 128m
    hostname: api
    environment:
      - REDIS_HOST=$REDIS_HOST
      - REDIS_PORT=$REDIS_PORT
      - PGUSER=$PGUSER
      - PGHOST=$PGHOST
      - PGDATABASE=$PGDATABASE
      - PGPASSWORD=$PGPASSWORD
      - PGPORT=$PGPORT
  
  worker:
    image: 'devopsdmc/fibworker'
    mem_limit: 128m
    hostname: worker
    environment: 
      - REDIS_HOST=$REDIS_HOST
      - REDIS_PORT=$REDIS_PORT
  
  nginx:
    image: 'devopsdmc/fibnginx'
    mem_limit: 128m
    hostname: nginx
    ports:
      - '80:80'